name: Auto Raylib Android

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Clone Raylib
      run: |
        git clone --depth 1 https://github.com/raysan5/raylib.git

    - name: Copy Android Project
      run: |
        cp -r raylib/projects/Android project

    - name: Replace main.c
      run: |
        cp main.c project/app/src/main/cpp/main.c

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    - name: Install NDK
      run: |
        yes | sdkmanager --licenses
        sdkmanager "ndk;25.2.9519653"

    - name: Build APK
      run: |
        cd project
        chmod +x gradlew
        ./gradlew assembleRelease

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: Geometrium
        path: project/app/build/outputs/apk/release/app-release.apk
